name: Build and Deploy Banking Spring App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Banking SpringBoot Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn package --batch-mode -DskipTests

      - name: Build Docker Image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME}}/Royal-Banking-Application:$(date-'%Y-%m-%d%H-%M-%S')
